#propagate commands to run all by all blast on 26 NAM genomes 

declare -a GFF=("/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/B73_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/B97_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/CML103_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/CML228_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/CML247_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/CML277_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/CML322_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/CML333_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/CML52_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/CML69_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/HP301_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/Il14H_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/Ki11_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/Ki3_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/Ky21_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/M162W_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/M37W_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/Mo18W_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/Ms71_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/NC350_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/NC358_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/Oh43_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/Oh7B_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/P39_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/Tx303_evidence.abinitio_annotation_canonical_ts.gff"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files/Tzi8_evidence.abinitio_annotation_canonical_ts.gff"
"test")

declare -a DB=("/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/B73_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/B97_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/CML103_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/CML228_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/CML247_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/CML277_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/CML322_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/CML333_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/CML52_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/CML69_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/HP301_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/Il14H_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/Ki11_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/Ki3_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/Ky21_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/M162W_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/M37W_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/Mo18W_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/Ms71_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/NC350_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/NC358_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/Oh43_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/Oh7B_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/P39_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/Tx303_cds_db"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/blast_dir/Tzi8_cds_db"
"test")

declare -a LINES=("B73"
"B97"
"CML103"
"CML228"
"CML247"
"CML277"
"CML322"
"CML333"
"CML52"
"CML69"
"HP301"
"Il14H"
"Ki11"
"Ki3"
"Ky21"
"M162W"
"M37W"
"Mo18W"
"Ms71"
"NC350"
"NC358"
"Oh43"
"Oh7B"
"P39"
"Tx303"
"Tzi8"
"test")

declare -a CDS=("/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/B73_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/B97_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML103_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML228_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML247_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML277_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML322_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML333_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML52_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML69_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/HP301_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Il14H_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Ki11_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Ki3_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Ky21_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/M162W_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/M37W_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Mo18W_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Ms71_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/NC350_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/NC358_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Oh43_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Oh7B_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/P39_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Tx303_canonical_ts.fasta"
"/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Tzi8_canonical_ts.fasta"
"test")

declare -a SPLIT=("ag"
"bg"
"cg"
"dg"
"eg"
"fg"
"gg"
"hg"
"ig"
"jg"
"kg"
"lg"
"mg"
"ng"
"og"
"pg"
"qg"
"rg"
"sg"
"tg"
"ug"
"vg"
"wg"
"xg"
"yg"
"zg"
"test")


COORDS="/home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/nucmer_output"

for QUERY in {0..26}; do
    for SUBJECT in {0..26}; do
        # We don't want to compare the same line to itself                                                                                                                                             
        if [ "$QUERY" -ne "$SUBJECT" ]; then
        (echo python3 All_by_All_Blast_COedits.py \
            -q ${GFF[$QUERY]} \
            -s ${GFF[$SUBJECT]} \
            -b ${DB[$SUBJECT]} \
            -l ${CDS[$QUERY]} \
            -o /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/all_by_all_output/${LINES[$QUERY]}_${LINES[$SUBJECT]}_AllbyAll_res.txt \
            -n ${COORDS}/${LINES[$QUERY]}_${LINES[$SUBJECT]}_c1000.fil.coords \
            -g ${SPLIT[$SUBJECT]} )
        fi
    done
done
