makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/B73_canonical_ts.fasta -out B73_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/B97_canonical_ts.fasta -out B97_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML103_canonical_ts.fasta -out CML103_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML228_canonical_ts.fasta -out CML228_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML247_canonical_ts.fasta -out CML247_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML277_canonical_ts.fasta -out CML277_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML322_canonical_ts.fasta -out CML322_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML333_canonical_ts.fasta -out CML333_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML52_canonical_ts.fasta -out CML52_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/CML69_canonical_ts.fasta -out CML69_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/HP301_canonical_ts.fasta -out HP301_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Il14H_canonical_ts.fasta -out Il14H_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Ki11_canonical_ts.fasta -out Ki11_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Ki3_canonical_ts.fasta -out Ki3_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Ky21_canonical_ts.fasta -out Ky21_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/M162W_canonical_ts.fasta -out M162W_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/M37W_canonical_ts.fasta -out M37W_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Mo18W_canonical_ts.fasta -out Mo18W_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Ms71_canonical_ts.fasta -out Ms71_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/NC350_canonical_ts.fasta -out NC350_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/NC358_canonical_ts.fasta -out NC358_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Oh43_canonical_ts.fasta -out Oh43_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Oh7B_canonical_ts.fasta -out Oh7B_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/P39_canonical_ts.fasta -out P39_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Tx303_canonical_ts.fasta -out Tx303_cds_db -dbtype nucl
makeblastdb -in /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/longest_transcript_files/Tzi8_canonical_ts.fasta -out Tzi8_cds_db -dbtype nucl
