#commands to create new gene names for combined ab initio and evidence based genes
#input gff files were already sorted by position when they were created so new gene name numbers should reflect order 
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/B73_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10001ag%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/B73_abinitio_evidence_gene.name.key.txt 
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/B97_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10018bg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/B97_abinitio_evidence_gene.name.key.txt 
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML103_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10021cg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML103_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML228_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10022dg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML228_abinitio_evidence_gene.name.key.txt 
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML247_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10023eg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML247_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML277_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10024fg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML277_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML322_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10025gg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML322_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML333_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10026hg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML333_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML52_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10019ig%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML52_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML69_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10020jg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/CML69_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/HP301_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10027kg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/HP301_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Il14H_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10028lg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Il14H_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Ki11_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10030mg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Ki11_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Ki3_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10029ng%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Ki3_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Ky21_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10031og%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Ky21_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/M162W_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10033pg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/M162W_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/M37W_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10032qg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/M37W_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Mo18W_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10034rg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Mo18W_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Ms71_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10035sg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Ms71_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/NC350_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10036tg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/NC350_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/NC358_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10037ug%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/NC358_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Oh43_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10039vg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Oh43_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Oh7B_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10038wg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Oh7B_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/P39_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10040xg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/P39_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Tx303_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10041yg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Tx303_abinitio_evidence_gene.name.key.txt
grep -v "^#" /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Tzi8_abinitio_evidence.gff3 | grep "	gene" | cut -f 9 | sed -e 's/gene://' | tr "=" "\t" | tr ";" "\t" | cut -f 2 | awk '{print $1"\t"NR}' | awk -F "\t" '{printf "%s\tZm10042zg%06i\n", $1,$2}' > /home/hirschc1/oconnorc/SplitGenes/NAM_genome_comparisons/gff_files_oldname/Tzi8_abinitio_evidence_gene.name.key.txt
